var Chances={
	"Argentina" : "0%",
	"Germany" : "0%",
	"Netherlands" : "49.6%",
	"Brazil" : "0%",
	"Uruguay" : "0%",
	"Spain" : "50.4%",
	"Portugal" : "0%",
	"Ghana" : "0%",
	"Chile" : "0%",
	"Japan" : "0%",
	"Paraguay" : "0%",
	"Slovakia" : "0%",
	"Mexico" : "0%",
	"Korea Republic" : "0%",
	"England" : "0%",
	"USA" : "0%",
	"South Africa" : "0%",
	"France" : "0%",
	"Greece" : "0%",
	"Nigeria" : "0%",
	"Algeria" : "0%",
	"Slovenia" : "0%",
	"Serbia" : "0%",
	"Australia" : "0%",
	"Cameroon" : "0%",
	"Denmark" : "0%",
	"Italy" : "0%",
	"New Zealand" : "0%",
	"C™te d'Ivoire" : "0%",
	"Korea DPR" : "0%",
	"Honduras" : "0%",
	"Switzerland" : "0%"
}