var Chances={
	"Argentina" : "21.3%",
	"Germany" : "16%",
	"Netherlands" : "15.3%",
	"Brazil" : "14.7%",
	"Uruguay" : "9.3%",
	"Spain" : "9.1%",
	"Portugal" : "6.6%",
	"Ghana" : "3.4%",
	"Chile" : "1.4%",
	"Japan" : "1.3%",
	"Paraguay" : "1.1%",
	"Slovakia" : "0.3%",
	"Mexico" : "0%",
	"Korea Republic" : "0%",
	"England" : "0%",
	"USA" : "0%",
	"South Africa" : "0%",
	"France" : "0%",
	"Greece" : "0%",
	"Nigeria" : "0%",
	"Algeria" : "0%",
	"Slovenia" : "0%",
	"Serbia" : "0%",
	"Australia" : "0%",
	"Cameroon" : "0%",
	"Denmark" : "0%",
	"Italy" : "0%",
	"New Zealand" : "0%",
	"C™te d'Ivoire" : "0%",
	"Korea DPR" : "0%",
	"Honduras" : "0%",
	"Switzerland" : "0%"
}